spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    username: root
    url: jdbc:mysql://localhost:3306/book?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

